Correct
VladislavBrykov/TypeScript_Authorization_SqLite pull request #4
Opened 2021-08-12 09:53 UTC by VladislavBrykov

2021-08-12 10:38 UTC, roman1bondarenko requested changes

2021-08-12 10:38 UTC, roman1bondarenko commented on Api-Router/Users/user.controller.ts
> +    return (resRegistration ? res.status(200).json({ status: 'registration successful' }) : res.status(404).json({ status: 'registration error, user exists' }))
return resRegistration ? 
       res.status(200).json({ status: 'registration successful' }) : 
       res.status(404).json({ status: 'registration error, user exists' })

2021-08-12 10:38 UTC, roman1bondarenko commented on Api-Router/Users/user.controller.ts
> +    req.url.indexOf('true') >= 0 ? all : all = null
express query params

2021-08-12 10:38 UTC, roman1bondarenko commented on Api-Router/Users/user.controller.ts
> +    req.url.indexOf('true') >= 0 ? all : all = null
PLUS check express core and features!!!!
http://expressjs.com/en/4x/api.html#req.params?foo=qwertyu

2021-08-12 10:38 UTC, roman1bondarenko commented on Service/Users/users.servece.data.ts
> +        all ? UserDevice.update({ token: null }, { where: { token: token } }) : User.update({ token: null }, { where: { phoneEmail: searchUser.phoneEmail } })
all ? 
         UserDevice.update({ token: null }, { where: { token: token } }) : 
         User.update({ token: null }, { where: { phoneEmail: searchUser.phoneEmail } });


check DB models!!!

2021-08-12 10:38 UTC, roman1bondarenko commented on Service/Users/utils/user.service.helpers.ts
> +        await updateObject(UserDevice);
Promise.all();

2021-08-12 10:38 UTC, roman1bondarenko commented on Service/Users/utils/user.service.helpers.ts
> +
use nore generic function and check again DB models and structure :)

2021-08-12 13:20 UTC, merged

2021-08-13 09:18 UTC, VladislavBrykov commented on Service/Users/utils/user.service.helpers.ts
> +
I use table User, because in this table save params typeId. Structure is correct